insert into PERSON (username, real_name, profile_picture, birthday) values ('jane', 'Jane Doe', 'R.drawable.cat_sporty', '9/25/1993');
insert into PERSON (username, real_name, profile_picture, birthday) values ('demia', 'Demia Kurniasih', 'R.drawable.cat_sporty', '10/10/1994');
insert into PERSON (username, real_name, profile_picture, birthday) values ('kasel', 'Kasel Setyawan', 'R.drawable.cat_sporty', '6/30/1994');
insert into PERSON (username, real_name, profile_picture, birthday) values ('laias', 'Laias Asih', 'R.drawable.cat_sporty', '5/6/1993');
insert into PERSON (username, real_name, profile_picture, birthday) values ('aisha', 'Siti Aisha', 'R.drawable.cat_sporty', '7/31/1995');
insert into STAT_HISTORY (username, timestamp, height, weight) values ('aisha', 1511369167, 154, 47);
insert into STAT_HISTORY (username, timestamp, height, weight) values ('jane', 1511369167, 157, 52);
insert into STAT_HISTORY (username, timestamp, height, weight) values ('demia', 1511369167, 164, 56);
insert into STAT_HISTORY (username, timestamp, height, weight) values ('kasel', 1511369167, 174, 78);
insert into STAT_HISTORY (username, timestamp, height, weight) values ('laias', 1511369167, 170, 52);
insert into CHAT_ROOM (chat_id) values (1);
insert into CHAT_ROOM (chat_id) values (2);
insert into GROUP_CHAT_ROOM (chat_id, name, group_picture) values (1, 'Runners', NULL);
insert into CHAT_MEMBERS (chat_id, username) values (1, 'jane');
insert into CHAT_MEMBERS (chat_id, username) values (1, 'demia');
insert into CHAT_MEMBERS (chat_id, username) values (1, 'kasel');
insert into CHAT_MEMBERS (chat_id, username) values (1, 'laias');
insert into CHAT_MEMBERS (chat_id, username) values (1, 'aisha');
insert into PRIVATE_CHAT_ROOM (chat_id, username) values (2, 'demia');
insert into CHAT_ITEM (chat_id, username, timestamp, content) values (1, 'laias', 1511369168, 'halo');
insert into CHAT_ITEM (chat_id, username, timestamp, content) values (2, 'demia', 1511369170, 'hai');